model:
  lr: 1e-4
  n_layers: 2
  hidden_dims: 128

dataset:
  dataset_path: data/nowplaying_rs_dataset.pkl
  n_layers: ${model.n_layers}
  batch_size: 32
  num_workers: 16

trainer:
  max_epochs: 5
  gpus: 0
  log_every_n_steps: 1000

num_epochs: ${trainer.max_epochs}
