model:
  lr: 2e-5
  n_layers: 2

dataset:
  dataset_path: data/nowplaying_rs_dataset.pkl
  n_layers: ${model.n_layers}

trainer:
  max_epochs: 5

batches_per_epoch: 100
num_epochs: ${trainer.max_epochs}
